use clap::{Parser, Subcommand};
use std::path::PathBuf;

#[derive(Parser, Debug)]
#[command(name = "wt")]
#[command(about = "Manage git worktrees next to the current repository")]
pub struct Cli {
    #[command(subcommand)]
    pub command: Commands,
}

#[derive(Subcommand, Debug)]
pub enum Commands {
    /// Print shell integration so `wt open <target>` can cd the current shell.
    Init,
    /// Create a managed worktree in ../<repo>-worktrees/<name>.
    Create {
        /// Worktree name. Also used as the branch name unless --branch is set.
        name: String,
        /// Branch to check out or create.
        #[arg(short, long)]
        branch: Option<String>,
        /// Starting point when creating a new branch.
        #[arg(short = 'B', long, default_value = "HEAD")]
        base: String,
        /// Reuse an existing branch instead of creating a new one.
        #[arg(long)]
        existing: bool,
        /// Directory inside the repo to open for this worktree. Defaults to the current relative directory.
        #[arg(short, long)]
        root: Option<PathBuf>,
        /// Do not open the new worktree in cmux after creating it.
        #[arg(long)]
        no_open: bool,
    },
    /// List managed worktrees.
    List {
        /// Include the main worktree and unmanaged linked worktrees.
        #[arg(short, long)]
        all: bool,
    },
    /// Open a worktree in a new cmux workspace, or run a command inside it.
    Open {
        /// Worktree name, branch name, or path.
        target: String,
        /// Command to run in the worktree. If omitted, opens a new cmux workspace.
        #[arg(short = 'c', long)]
        command: Option<String>,
        /// cmux workspace title. Defaults to a compact worktree/branch title.
        #[arg(short, long)]
        title: Option<String>,
        /// Directory inside the target worktree to open. Defaults to the saved root, then the current relative directory.
        #[arg(short, long)]
        root: Option<PathBuf>,
        /// Keep the cmux workspace title generated by cmux.
        #[arg(long)]
        no_rename: bool,
        /// Pin the cmux workspace after opening it.
        #[arg(long)]
        pin: bool,
    },
    /// Print the resolved path for a worktree.
    #[command(hide = true)]
    Path {
        /// Worktree name, branch name, or path.
        target: String,
    },
    /// Merge a managed worktree branch, remove the worktree, and close its cmux workspace.
    Merge {
        /// Worktree name, branch name, or path.
        target: String,
        /// Destination branch. Defaults to the current branch in the main worktree.
        #[arg(long)]
        into: Option<String>,
        /// Keep the source branch after a successful merge.
        #[arg(long)]
        keep_branch: bool,
    },
    /// Delete a managed worktree.
    Delete {
        /// Worktree name, branch name, or path.
        target: String,
        /// Remove even when the worktree has uncommitted changes.
        #[arg(short, long)]
        force: bool,
        /// Delete the branch after removing the worktree.
        #[arg(long)]
        delete_branch: bool,
    },
}
